[target.x86_64-pc-windows-gnullvm]
linker = "rust-lld"

[build]
rustflags = [
    "-C", "linker=rust-lld",
    "-L", "native=C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\um\\x64",
    "-L", "native=C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.26100.0\\ucrt\\x64"
]
